name: Build and Release ServiceMonitor

on:
  push:
    tags:
      - 'v*'    # workflow запускается при пуше тега, например v1.0.0
  workflow_dispatch: 
    inputs:
      tag_name:
        description: 'Tag to release'
        required: true
        default: 'v1.0.0'
  
jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: 'ServiceMonitor.sln'
      Project_Path: 'ServiceMonitor.csproj'
      Publish_Dir: './publish'
      Zip_File: 'ServiceMonitor.zip'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build solution
      run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ${{ env.Solution_Name }} --configuration Release --no-build --verbosity normal

    - name: Publish application
      run: dotnet publish ${{ env.Project_Path }} --configuration Release --output ${{ env.Publish_Dir }} /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true /p:PublishTrimmed=false

    - name: Zip published files
      run: |
        powershell Compress-Archive -Path ${{ env.Publish_Dir }}\* -DestinationPath ${{ env.Zip_File }}

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: Automated release from GitHub Actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: ServiceMonitor.zip
        asset_path: ${{ env.Zip_File }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
